### ISSUE TITLE
Milestone 1: wifi with preconfigured SSID/password

### ISSUE THREAD

**Issue by drbild** [xaptum/xaprc#1]
### Requirements

Milestone 1 consists of a host driver and firmware for the XAP-RW-001 router card that

1) connects the WiFi chipset on the router card to one of a set of pre-configured access points.
2) establishes a control tunnel `enf1` on the router card via the WiFi. All local traffic on the router card (e.g., firmware updates) should be routed via this interface.
3) Establishes a virtual interface `enf0` on the host and associated tunnel `enf0` on the router card via the WiFi.  Traffic to/from the virtual interface `enf0` on the host should be routed via this tunnel.

### Implementation Tasks

The following list tracks the tasks required to implement this milestone.  The linked issues have additional details.

- [x] [xaptum-buildroot/#6](https://github.com/xaptum/xaptum-buildroot/issues/6) Manage the WiFi connection on the target.
- [x] [xaptum-buildroot/#3](https://github.com/xaptum/xaptum-buildroot/issues/3) Bring up `enf0` and `enf1` tunnels on the target.
- [x] [xaprc/#2](https://github.com/xaptum/xaprc/issues/2) Create usbnet-based host driver and target to operate virtual interface `enf0`.
- [x] [xaprc/#2](https://github.com/xaptum/xaprc/issues/2) Inject packets from the host into the `enf0` tunnel on the target.
- [x] []() Set IPv6 address on host `enf0` interface.

### Verification

1) The first verification test scenario is a simple ping test between two hosts containing XAP-RW-001 router cards.

    The router cards should be connected to an available local access point and each host configured to route IPv6 traffic via the `enf0` interface.  A ping from the first host to the ENF IPv6 address of the second should receive a response.

2) The second verification test scenario is a simple `iperf` TCP bandwidth test between the two hosts.

    Again, the router cards should be connected to an available local access point and each host configured to route IPv6 traffic via the `enf0` interface.  The `iperf` server mode should be run on one host and the `iperf` client on the other. A TCP throughput of 10 kbps should be achieved.
